remote_theme: andreondra/jekyll-theme-simplex

title: Sergey Ichtchenko
email: sergey@sergey.fi
description: >-
  A Computer Science and Mathematics undergraduate.
  Working as a Cyber Security Consultant.
baseurl: ""
url: "https://sergey.fi"

logo_img: assets/supers.png
copyright: © Sergey Ichtchenko 2022

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
