remote_theme: andreondra/jekyll-theme-simplex

# logo_img: 
copyright: © Sergey Ichtchenko 2022

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
