remote_theme: PixelSergey/jekyll-theme-simplex

title: Sergey Ichtchenko
email: sergey@sergey.fi
description: >-
  PhD stduent in Computer Science at Oxford.
  I love cyber security, aviation, and cool nerdy maths stuff! 
baseurl: ""
url: "https://sergey.fi"

logo_img: /assets/supers.png
favicon: /assets/supers.png
copyright: © Sergey Ichtchenko

include: ["sergey.pgp"]
timezone: "Europe/Helsinki"

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
